"""Numbered SQL migrations, applied in filename order.

Plain SQL rather than Alembic: the schema is small enough to read directly,
and an interviewer asking "what does your chunks table look like" is better
served by one readable file than by autogenerated revision chains.
"""

import asyncio
import hashlib
import sys
from pathlib import Path

from sqlalchemy import text

from app.config import get_settings
from app.db.session import engine
from app.runtime import use_compatible_event_loop

MIGRATIONS_DIR = Path(__file__).resolve().parents[2] / "migrations"

_TRACKING_TABLE = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    filename    TEXT PRIMARY KEY,
    checksum    TEXT NOT NULL,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""


def _render(sql: str) -> str:
    return sql.replace("{{EMBEDDING_DIM}}", str(get_settings().embedding_dim))


async def run_migrations() -> list[str]:
    applied: list[str] = []
    files = sorted(MIGRATIONS_DIR.glob("*.sql"))

    async with engine.begin() as conn:
        await conn.execute(text(_TRACKING_TABLE))
        rows = await conn.execute(text("SELECT filename, checksum FROM schema_migrations"))
        seen = dict(rows.all())

    for path in files:
        raw = path.read_text(encoding="utf-8")
        sql = _render(raw)
        # Checksum the rendered SQL, so changing EMBEDDING_DIM is caught as a
        # modified migration rather than silently leaving a mismatched column.
        checksum = hashlib.sha256(sql.encode()).hexdigest()[:16]

        if path.name in seen:
            if seen[path.name] != checksum:
                raise RuntimeError(
                    f"{path.name} changed after being applied "
                    f"(was {seen[path.name]}, now {checksum}). If EMBEDDING_DIM changed, "
                    "the vector column must be rebuilt and the corpus re-embedded."
                )
            continue

        async with engine.begin() as conn:
            await conn.execute(text(sql))
            await conn.execute(
                text(
                    "INSERT INTO schema_migrations (filename, checksum) VALUES (:f, :c)"
                ),
                {"f": path.name, "c": checksum},
            )
        applied.append(path.name)

    return applied


def main() -> None:
    use_compatible_event_loop()
    applied = asyncio.run(run_migrations())
    if applied:
        print("applied:", ", ".join(applied))
    else:
        print("schema up to date")


if __name__ == "__main__":
    sys.exit(main())
